# Generated by Django 2.0.5 on 2018-05-19 23:56

from django.db import migrations
from wagtail.core.models import Collection


def create_collections(apps, schema_editor):
    names = [
        'team videos',
        'varied videos',
        'team images',
        'varied images',
        'team documents',
        'varied documents',
        'logos',
        'landing page',
        'profile photos',
        'feed images',
        'products',
        'engine',
        'maintenance',
        'ground support',
        'aviation',
        'cases',
        'cabin interior',
        'brochure',
        'services',
        'design'
    ]

    # Get collection's root
    root_collection = Collection.get_first_root_node()

    for name in names:
        root_collection.add_child(name=name)


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.RunPython(create_collections, reverse_code=migrations.RunPython.noop),
    ]
