# Generated by Django 2.0.5 on 2018-05-20 00:10

from django.db import migrations
from django.utils.text import slugify


def create_tags(apps, schema_editor):
    Tag = apps.get_model('taggit.Tag')
    names = [
        'content',
        'services',
        'works',
        'news',
        'quality',
        'planes',
        'products',
        'tools',
        'equipment',
        'shipping',
        'storage',
        'components',
        'supplies',
        'jacks',
        'container',
        'development',
        'production',
        'application'
    ]

    for name in names:
        Tag.objects.create(
            name=name,
            slug=slugify(name)
        )


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0003_create_default_collections'),
    ]

    operations = [
        migrations.RunPython(create_tags, reverse_code=migrations.RunPython.noop),
    ]
